# Generated by Django 6.0 on 2025-12-16 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_blog_word_count"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="blog",
            options={
                "permissions": [
                    ("change_blog_title", "Peut changer le titre d'un billet de blog")
                ]
            },
        ),
    ]
