# Generated by Django 6.0 on 2025-12-16 12:58

from django.db import migrations

def authot_to_contributors(apps, schema_migration):
    Blog = apps.get_model('blog', 'Blog')
    for blog in Blog.objects.all():
        if blog.author:
            blog.contributors.add(
                blog.author, through_defaults={'contribution': 'Auteur principal'})


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_alter_blog_author_blogcontributor_blog_contributors"),
    ]

    operations = [
        migrations.RunPython(authot_to_contributors)
    ]
