# Generated by Django 6.0 on 2025-12-16 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0005_auto_20251216_1358"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blog",
            name="author",
        ),
    ]
